### PR TITLE
httpd: fix upload file with Firefox

### LINKED ISSUE #2: Web interface functionality appears broken
I get a connection reset after uploading firmware via the web interface, but TFTP works just fine.

### PR DESCRIPTION
**Pull request by rany2**
Closes #2

### CODE REVIEW

**Comment by DragonBluep** [comment]
Thank you for fixing this issue.

**Comment by rany2** [comment]
@DragonBluep Most welcome, though I'm curious; when you said "most users reported compat issues..."; is there some forum thread for this project? If so, could you link to it?

**Comment by DragonBluep** [comment]
Yes, I once posted it on a Chinese forum. However, it's difficult to get an account, I have given up using it. All necessary instructions have been moved to the readme file.
https://www.right.com.cn/forum/thread-8256710-1-1.html

**Comment by rany2** [comment]
I see, I do not know any Mandarin so this is not very useful for me. Besides, the website is very slow to load and keeps failing for me; I have heard that the Chinese internet speed to the rest of the world is not very good because of insufficient infrastructure and throttling which I guess would explain it not working for me.

Thanks for the information anyway! (P.S. I've only stumbled across your page because of your participation in OpenWRT, was curious to check your work :))

**Pull request merged**
